image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - test
  - deploy-staging
  - deploy-production

test:
  stage: test
  script:
    - npm i npm@latest -g
    - npm i
    - npm test

deploy-staging:
  type: deploy
  stage: deploy-staging
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

deploy-production:
  type: deploy
  stage: deploy-production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
